### PR TITLE
Updating the page's title based on the route.

### LINKED ISSUE #67: App title
App `title` should be "Best Books for Kids" and "Best Books for Teens" respectively. Currently is "NYPL | Recommendations".

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes #67 

The page's title should now read either "Best Books for Teens" or "Best Books for Kids".

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
@wlla @courtneymcgee what do you say regarding @rhernand3z comment above?

**Comment by courtneymcgee** [comment]
For SCC, we did
Shared Collection Catalog | NYPL

I'd recommend
Best Books for Kids | NYPL
to stay consistent

@wlla, ok with you?

**Comment by wlla** [comment]
:+1:  Good catch.

**Comment by EdwinGuzman** [comment]
Updated. Thanks.

**Pull request merged**
