### PR TITLE
Fixing GA events for list dropdowns.

### PR DESCRIPTION
**Pull request by EdwinGuzman**
The list dropdowns were not correctly rendering the proper values. Updated them.

FYI @courtneymcgee .

### CODE REVIEW

**Comment by holingpoon** [comment]
On [dev-www Google Analytics](https://analytics.google.com/analytics/web/#/report/content-event-events/a1420324w81765235p84655146/_r.drilldown=analytics.eventCategory:Staff%20Picks,analytics.eventAction:Lists&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=10/), these are the top 10 values appeared in GA Events:

1. [object Object] - Children	
2. [object Object] - YA	
3. 2015	
4. 2017-06-01 - [object Object]	
5. 2014	
6. 2015-08 - [object Object]	
7. 2016
8. 2018-01-01 - [object Object]	
9. 2017-09-01 - [object Object]
10. 2015-10 - [object Object]

So does this mean only the values 'Adult', 'YA', and 'Children' would show up on analytics?

**Comment by EdwinGuzman** [comment]
Right, `[object Object]` will not show up anymore.

**Comment by ktp242** [comment]
Staff Picks lists work well!!

On YA and Children lists, I will get the following message if I switch among years

```
react-ga] with fieldObject: {"hitType":"event","eventCategory":"Staff Picks","eventAction":"Lists","eventLabel":"2014"}
```

Probably should change the category from Staff Picks to YA or Children?

**Comment by EdwinGuzman** [comment]
Hmmm no. It should be "Best Books" and we should differentiate at a lower level if it's staff picks, ya, or children.

**Comment by EdwinGuzman** [comment]
Hmmm no. It should be "Best Books" and we should differentiate at a lower level if it's staff picks, ya, or children.

**Comment by EdwinGuzman** [comment]
Updated the spreadsheet https://docs.google.com/spreadsheets/d/11e52iPS_oEnkkcUOZyd7EMcZJG5DFdtzA21Hn0lWndg/edit#gid=0

Will update this PR soon.

**Comment by EdwinGuzman** [comment]
Updated the GA event `Action`s labels to better categorize between `YA`, `Childrens`, and `Staff Picks`. @courtneymcgee I updated the spreadsheet to include this update.

**Comment by EdwinGuzman** [comment]
Updated.

**Pull request merged**
