### PR TITLE
Quick fix - making the image height bigger so that the byline doesn't…

### PR DESCRIPTION
**Pull request by EdwinGuzman**
… float down the card.

Quick fix for @ricardogalvez .

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
That I don't see. Screenshot?

**Comment by gkallenberg** [comment]
Screen shots from the current Staff Picks Adult list.
screen shot 2018-05-10 at 12 58 13 pm
screen shot 2018-05-10 at 12 58 02 pm
screen shot 2018-05-10 at 12 57 51 pm

**Comment by EdwinGuzman** [comment]
It's because the height is _still_ not big enough. I'll just make it bigger.

**Comment by ktp242** [comment]
Codes look good. If @ricardoom feels OK with the outcome then I think it can be approved.

**Pull request merged**
