### PR TITLE
Chopped off mobile text

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Fixes (hopefully) #128 

I just add less space to the left of the h2 and the span. The ^ and down arrow button overlaps the text since it's positioned absolute. Let me know if this works.

### CODE REVIEW

**Comment by chrismulholland** [comment]
I'm not seeing on change on my iPhone 5.  "found" is still cut off.

**Comment by EdwinGuzman** [comment]
Still just as much as before?

**Comment by chrismulholland** [comment]
yeah

**Comment by chrismulholland** [comment]
on iPhone 5, I compared to screenshot from earlier.  Looks like you've gained almost a full character.  On your way!

**Comment by EdwinGuzman** [comment]
Checke again please, @chrismulholland .

**Comment by chrismulholland** [comment]
looks good on my iphone 5.  how about your phone, @courtneymcgee ?

**Comment by courtneymcgee** [comment]
Checked on my phone on dev. Looks great, @chrismulholland and @EdwinGuzman!

**Comment by EdwinGuzman** [comment]
Great. Thanks.

One more thing, @chrismulholland can you check other mobile devices and make sure nothing looks off? It's a fix for one specific viewport but we still need to make sure everything else is still alright.

**Comment by chrismulholland** [comment]
will do

**Comment by chrismulholland** [comment]
good on the following mobile devices:

Galaxy Note 8
Pixel
Pixel XL
Galaxy S7
iPhone 7
iPhone 5
iPad Air 2

**Comment by EdwinGuzman** [comment]
Alright. Merging. Thanks again.

**Pull request merged**
